#!/bin/sh

set -euo pipefail

#
# This is advanced (Image)Magick.
#
# Feel free to not even trying understand this :-)
#
# The script was partially generated by AI.
#

# Inputs: no getopts, only positional arguments
output_filename="$1"
top_title_text="$2"
main_title_pango="$3"
thumb_filename="$4"
text_block_left_pango="$5"
text_block_right_pango="$6"



# Main geometry: update font sizes in templates if required

total_width=450
total_height=750

frame_margin=10
frame_radius=24
frame_width=2
frame_color="black"

main_title_height=90
main_title_y=405

thumb_width=400
thumb_height=300
thumb_frame_pad=6
thumb_frame_width=1
thumb_frame_radius=5
thumb_frame_color="white"

top_title_height=60
thumb_y=80

top_title_font_family="DejaVu-Sans"
top_title_font_size=24

text_block_y=485
text_block_height=220

text_block_left_width=240
text_block_right_width=105
text_block_column_gap=5




# Safety check
inner_text_width=$(( text_block_left_width + text_block_right_width + text_block_column_gap ))
if [ "${inner_text_width}" -gt $(( total_width - 40 )) ]; then
    echo "Error: text columns too wide" >&2
    exit 1
fi

# Column placement relative to canvas center
text_block_left_x=$(( -(text_block_right_width + text_block_column_gap) / 2 ))
text_block_right_x=$(( (text_block_left_width + text_block_column_gap) / 2 ))

# Outer frame rectangle
frame_x1=$(( frame_margin ))
frame_y1=$(( frame_margin ))
frame_x2=$(( total_width - frame_margin - 1 ))
frame_y2=$(( total_height - frame_margin - 1 ))

thumb_box_width=$(( thumb_width + 2 * thumb_frame_pad ))
thumb_box_height=$(( thumb_height + 2 * thumb_frame_pad ))

# Build the final image from individual subimages:
# - frame around the whole card
# - top title text (card number) is only annotated, rest is Pango-based
# - thumbnail image with its own frame
# - main title
# - left column
# - right column
magick \
   -size "${total_width}x${total_height}" xc:white \
   \
   \( \
      -size "${total_width}x${total_height}" xc:none \
      -stroke "${frame_color}" -strokewidth "${frame_width}" -fill none \
      -draw "roundrectangle ${frame_x1},${frame_y1} ${frame_x2},${frame_y2} ${frame_radius},${frame_radius}" \
      +repage \
   \) \
   -gravity center -composite +gravity \
   \
   \( \
      -size "${total_width}x${top_title_height}" xc:none \
      -gravity northeast \
      -font "${top_title_font_family}" -pointsize "${top_title_font_size}" -fill black \
      -annotate +40+30 "${top_title_text}" \
      +repage \
   \) \
   -gravity north \
   -composite \
   +gravity \
   \
   \( \
         -size "${thumb_box_width}x${thumb_box_height}" xc:white \
         -stroke "${thumb_frame_color}" -strokewidth "${thumb_frame_width}" -fill none \
         -draw "roundrectangle 1,1 $((thumb_box_width-2)),$((thumb_box_height-2)) ${thumb_frame_radius},${thumb_frame_radius}" \
         "${thumb_filename}" \
         -gravity center \
         -composite \
         +repage \
   \) \
   -gravity north -geometry "+0+${thumb_y}" -composite +gravity \
   \
   \( \
      -background white \
      -size "${thumb_box_width}x${main_title_height}" \
      -define pango:align=center \
      -define pango:justify=false \
      "pango:${main_title_pango}" \
      +repage \
   \) \
   -gravity north \
   -geometry "+0+${main_title_y}" \
   -composite \
   +gravity \
   \
   \( \
      -background white \
      -size "${text_block_left_width}x${text_block_height}" \
      -define pango:align=left \
      -define pango:justify=false \
      "pango:${text_block_left_pango}" \
      +repage \
   \) \
   -gravity north \
   -geometry "+${text_block_left_x}+${text_block_y}" \
   -composite \
   +gravity \
   \
   \( \
      -background white \
      -size "${text_block_right_width}x${text_block_height}" \
      -define pango:align=right \
      -define pango:justify=false \
      "pango:${text_block_right_pango}" \
      +repage \
   \) \
   -gravity north \
   -geometry "+${text_block_right_x}+${text_block_y}" \
   -composite +gravity \
   \
   "${output_filename}"
