#!/usr/bin/env python3

import sys
import re

for line in sys.stdin:
	line = line.strip()

	pattern = r"^(ok|not ok)\s+\d+\s+(.*?) - (.*?) \((.*?)\)"
	
	match = re.search(pattern, line)
	if match:
		status_raw = match.group(1)
		suite = match.group(2)
		test_name = match.group(3)
		score_info = match.group(4)
	
		score = {"ok": 0, "fail": 0}
		parts = score_info.split(",")
		for part in parts:
			if "=" in part:
				key, val = part.split("=")
				score[key] = int(val)

		if status_raw == "ok":
			final_status = "passed"
			final_score = score["ok"]
		else:
			final_status = "failed"
			final_score = score["fail"]

			
		print(f"{final_status}:{final_score}:{suite}:{test_name}")
