#!/bin/bash

#   Script will split numbers into groups by three (first might be incomplete):
#     '+420123456789' ->  '+420 123 456 789'
#     '25000 Kč'      ->  '25 000 Kč'

set -euo pipefail

sed -E ':loop; s/([0-9])([0-9]{3})([^0-9]|$)/\1 \2\3/; t loop'
